controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - rot_joint_joint

   
    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

<<<<<<< HEAD:gillou/config/joint_control.yaml
  
=======

>>>>>>> 17f9372b11a7001e58022f9895c6e1e89a324b99:gillou/config/joint_control.yalm
